# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitTestSwiftCourseMock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnitTestSwiftCourseMock

  target 'UnitTestSwiftCourseMockTests' do
    inherit! :search_paths
    pod 'MockingbirdFramework', '~> 0.20'
  end

  target 'UnitTestSwiftCourseMockUITests' do
    # Pods for testing
  end

end
